version: "3.7"
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: secret 
            POSTGRES_USER: paliy 
            POSTGRES_DB: telegraph 
        volumes:
            - ./pgdata
        ports:
            - '5432:5432'
